.TH ACS 8 "6 June 2011" "acs" "Linux"
.SH NAME
acs \- compute the ideal channel to initiate radiation for 802.11 communication
.SH SYNOPSIS

.ad l
.in +8
.ti -8
.B acs [ dev ]

.ti -8
.IR OPTIONS " := { --version | --debug }"

.SH OPTIONS

.TP
.BR " --version"
print version information and exit.

.TP
.BR " --debug"
enable netlink message debugging.

.SH ACS - COMMAND SYNTAX

.SH SEE ALSO
.BR iw (8),
.BR ip (8),
.BR crda (8),
.BR regdbdump (8),
.BR regulatory.bin (5)

.BR http://wireless.kernel.org/en/users/Documentation/acs
