#!/bin/bash
#Enable NAT
echo 'Configuring NAT...' &> $NAT_LOGFILE
iptables --flush &>> $NAT_LOGFILE || exit
iptables --table nat --flush &>> $NAT_LOGFILE || exit
iptables --delete-chain &>> $NAT_LOGFILE || exit
iptables --table nat --delete-chain &>> $NAT_LOGFILE || exit
iptables --table nat --append POSTROUTING --out-interface $GENERAL_out -j MASQUERADE &>> $NAT_LOGFILE || exit
iptables --append FORWARD --in-interface $GENERAL_in -j ACCEPT &>> $NAT_LOGFILE || exit

#Thanks to lorenzo
#Uncomment the line below if facing problems while sharing PPPoE
#iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu &>> $NAT_LOGFILE
 
sysctl -w net.ipv4.ip_forward=1 &>> $NAT_LOGFILE || exit
