#!/usr/bin/env python
if __name__ == "__main__":
    import sys
    import pyrit_cli
    try:
        pyrit_cli.Pyrit_CLI().initFromArgv()
    except (KeyboardInterrupt, SystemExit):
        print >>sys.stderr, "\nInterrupted..."
    except pyrit_cli.PyritRuntimeError, e:
        sys.exit(e)
