import os

from main_window import font_size
from PyQt4 import QtCore, QtGui

font_setting = font_size()


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_attack_settings(object):
    def setupUi(self, attack_settings):
        attack_settings.setObjectName(_fromUtf8("attack_settings"))
        attack_settings.resize(400, 199)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/mac_address.png"%(os.getcwd()))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        attack_settings.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(attack_settings)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.mac_box = QtGui.QGroupBox(attack_settings)
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.mac_box.setFont(font)
        self.mac_box.setCheckable(True)
        self.mac_box.setChecked(False)
        self.mac_box.setObjectName(_fromUtf8("mac_box"))
        self.verticalLayout = QtGui.QVBoxLayout(self.mac_box)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.mac_box)
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mac_edit = QtGui.QLineEdit(self.mac_box)
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.mac_edit.setFont(font)
        self.mac_edit.setObjectName(_fromUtf8("mac_edit"))
        self.horizontalLayout.addWidget(self.mac_edit)
        spacerItem1 = QtGui.QSpacerItem(22, 21, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.mac_button = QtGui.QPushButton(self.mac_box)
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.mac_button.setFont(font)
        self.mac_button.setObjectName(_fromUtf8("mac_button"))
        self.horizontalLayout.addWidget(self.mac_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.mac_box)
        self.capture_box = QtGui.QGroupBox(attack_settings)
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.capture_box.setFont(font)
        self.capture_box.setCheckable(True)
        self.capture_box.setChecked(False)
        self.capture_box.setObjectName(_fromUtf8("capture_box"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.capture_box)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.capture_box)
        font = QtGui.QFont()
        font.setPointSize(font_setting)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.directory_label = QtGui.QLabel(self.capture_box)
        self.directory_label.setObjectName(_fromUtf8("directory_label"))
        self.horizontalLayout_2.addWidget(self.directory_label)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.direc_browse = QtGui.QPushButton(self.capture_box)
        self.direc_browse.setObjectName(_fromUtf8("direc_browse"))
        self.horizontalLayout_2.addWidget(self.direc_browse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.capture_box)

        self.retranslateUi(attack_settings)
        QtCore.QMetaObject.connectSlotsByName(attack_settings)

    def retranslateUi(self, attack_settings):
        attack_settings.setWindowTitle(QtGui.QApplication.translate("attack_settings", "WIFI Attack Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.mac_box.setTitle(QtGui.QApplication.translate("attack_settings", "Default MAC Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("attack_settings", "Set default MAC address to be used when attempting WIFI  attacks", None, QtGui.QApplication.UnicodeUTF8))
        self.mac_button.setText(QtGui.QApplication.translate("attack_settings", "Set MAC", None, QtGui.QApplication.UnicodeUTF8))
        self.capture_box.setTitle(QtGui.QApplication.translate("attack_settings", "Capture File Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("attack_settings", "Set Directory for storing capture files for offline usage", None, QtGui.QApplication.UnicodeUTF8))
        self.directory_label.setText(QtGui.QApplication.translate("attack_settings", "", None, QtGui.QApplication.UnicodeUTF8))
        self.direc_browse.setText(QtGui.QApplication.translate("attack_settings", "Browse", None, QtGui.QApplication.UnicodeUTF8))

