.TH OPENWIPS-NG 1 "JANUARY 2012" "Version 0.1 BETA"

.SH NAME
openwips-ng - A raw 802.11 frame capture tool. Sensor part of OpenWIPS-ng.

.SH SYNOPSIS
.B openwips-ng
<interface>
<server ip>
<port>
<login>
<pass>

.SH DESCRIPTION
.BI openwips-ng
captures and sends raw packets to the
.B openwips-ng-server(1).
It may also respond to attacks when ordered to by the
.B openwips-ng-server(1).

The
.B openwips-ng(1)
is one of the three parts in the
.B openwips-ng(1)
system.

.SH PARAMETERS
.TP
 <interface>
Monitor mode interface to use.
.TP
<server ip>
OpenWIPS-ng server's IP address.
.TP
<port>
OpenWIPS-ng server's (sensor) listening port.
.TP
<login>
Sensor's username.
.TP
<pass>
Sensor's password.

.SH AUTHOR
This manual page was written by Steve Cloutier <scloutier@openwips-ng.org>.
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation
.SH SEE ALSO
.br
.B openwips-ng-server(1)
