.TH MOEPEVAL 1 2014-5-5 "moep80211" "MOEP80211 Manual"
.SH NAME
moepeval \- a feature evaluator for moep80211
.SH SYNOPSIS
.B moepeval
.RI [ OPTION "]... " IF1 " " IF2
.SH DESCRIPTION
This program evaluates different driver and hardware features. Therefore it uses
the two radio interfaces IF1 and IF2.
.TP
.BR "-?" ", " "--help"
Give a help list
.TP
.BR "--usage"
Give a short usage message
.TP
.BR "-V" ", " "--version"
Print program version
.P
Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
.SH BUGS
Report bugs to <leclaire@in.tum.de>.
