.TH PTMSIMPLE 1 2014-5-5 "moep80211" "MOEP80211 Manual"
.SH NAME
ptmsimple \- a simple packet transfer module for moep80211
.SH SYNOPSIS
.B ptmsimple
.RI [ OPTION "]... " IF " " FREQ
.SH DESCRIPTION
This program translates between IEEE 802.3 and Moep 802.11. It creates a tap
device which can be used to access a Moep 802.11 network at a radio device via
IEEE 802.3. The radio interface IF is used on frequency FREQ [in MHz, you can
use M for MHz].
.TP
.BR "-a" ", " "--hwaddr" =\fIADDR
Set the hardware address to ADDR
.TP
.BR "-i" ", " "--ipaddr" =\fIADDR
Set the ip address to ADDR
.TP
.BR "-m" ", " "--mtu" =\fISIZE
Set the mtu to SIZE
.TP
.BR "-?" ", " "--help"
Give a help list
.TP
.BR "--usage"
Give a short usage message
.TP
.BR "-V" ", " "--version"
Print program version
.P
Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
.SH BUGS
Report bugs to <leclaire@in.tum.de>.
.SH SEE ALSO
.BR ptmbeacon (3)
