#!/bin/bash
# $0 <csv>
# e.g. 
# alexy@x200:~/wlan-pos$ ./tool/hide_coords dat/fpp_rawdata/moto/fpp_rawdata_moto_20101015.csv > tmp1.csv 


# 16col
#awk -F, 'BEGIN{OFS=","}{$12="";$13="";$14="";print}' $1
# 14col
awk -F, 'BEGIN{OFS=","}{$9="";$10="";$11="";print}' $1
