#!/bin/bash
# update soft links for req/ret.csv.

[ "$1" = "" ] && ( echo -e "\nType: $0 <tagname>\n"; exit 99 )
tag=$1

path="$PWD/dat/fpp_rawdata/cmri"
reqlnk=$path/req.csv
retlnk=$path/ret.csv
reqnew=$path/req_$tag.csv
retnew=$path/ret_$tag.csv
echo "removing old links..."
echo $reqlnk
echo $retlnk
rm $reqlnk $retlnk -f
echo "updating new links..."
echo $reqnew
echo $retnew
ln -s $reqnew $reqlnk
ln -s $retnew $retlnk
