#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          nidus (Nidus Storage Manager)
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initiates Nidus, the Wraith storage manager
### END INIT INFO

# Author: Dale Patterson <wraith.wireless@yandex.com>

# Change the next 3 lines to suit where script is installed and what its called
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/<user>/workspace/projects/Python/wraith/nidus/nidus.py
DAEMON_NAME=nidusd

# This next line determines what user the script runs as.
DAEMON_USER=<user>
 
# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

# source init functions
. /lib/lsb/init-functions

do_start() {
    log_daemon_msg "Starting $DAEMON_NAME"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pid --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
    log_end_msg $?
}

do_stop() {
    log_daemon_msg "Stopping $DAEMON_NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in
    start)
      do_start
     ;;
    stop)
      do_stop
     ;;
    restart)
      do_stop
      do_start
     ;;
    status)
     status_of_proc "$DAEMON_NAME" && exit 0 || exit $?
     ;;
    *)
      echo "Usage: /etc/init.d/nidusd {start|stop|restart|status}"
      exit 1
     ;;
esac