#!/usr/bin/env python

# (C) 2015 by Tomasz bla Fortuna
# License: GPLv2

"""
Entry point for WifiStalker tool.
"""

try:
    from wifistalker import main
except ImportError:
    print "Unable to find and import the `wifistalker' module - make sure it's"
    print "installed in your site-packages/dist-packages directories or available"
    print "at PYTHONPATH environment"
    print
    raise

if __name__ == "__main__":
   main.run()
