#!/bin/sh

if [ ! -d ".svn/" ]
then
	echo "0"
	exit ;
fi

REV="`svn info 2> /dev/null | grep -i revision | awk -F\  '{ print $2}'`"

if [ x$REV = "x" ]
then
	REV="`svnversion | awk -F: '{ print $2 }' | sed 's/[^0-9]*//g'`"
	if [ x$REV = "x" ]
	then
		REV="`svnversion | sed 's/[^0-9]*//g'`"
		if [ x$REV = "x" ]
		then
			REV="0"
		fi
	fi
fi

echo $REV