.TH AIRPWN 1 "Jun 30, 2006" "1NSuB" "Airpwn Users Manual"
.SH NAME
airpwn \- A network security utility 
.SH SYNOPSIS
.B airpwn -i iface -c configfile -d drivername  [-M -C -I -l -f -h -v -k -F]
.LP
.RI 
.SH DESCRIPTION
This manual page documents briefly the
.B airwpn
command.
.PP
.B airpwn  
is a thoughtful framework for automated injection of arbitrary application-layer data on an unencrypted 802.11 network. It is used mainly for penetration testing as it's primary role is for a complex pattern matching and packet generation.
.SH OPTIONS
This program doesn't follow the usual GNU command line syntax.
A summary of options is included below.
.TP
.B \-i
the interface to listen/control/inject with.  Equivalent of setting -M
-C and -I to the same interface.
.TP
.B \-M
specifies the interface to monitor for packets.  This interface must
support monitor mode.
.TP
.B \-C
specifies the interface to use for control.  (Right now this is only
used for changing channels.)
.TP
.B \-I
specifies the interface to use for packet injection.  This interface
MUST support the ability to inject raw packets.  For atheros, this
likely is ath0raw.
.TP
.B \-d
the driver name used for the specified interface (e.x. "hostap", "prism54", "madwifiold", "madwifing")
.TP
.B \-c
the location of the configuration file
.TP
.B \-l
the location of the file targeted for verbose logging
.TP
.B \-f
bpf filter for libpcap
.TP
.B \-k
WEP key for packet de/encryption.  May be used multiple times to specify
multiple keys
.TP
.B \-F
Assume no FCS headers at the end of the 802.11 frames.  Some drivers append
these and others don't.  If WEP decryption is failing when you're positive you
have the correct key, try using/not using -F.
.TP
.B \-h
quick help information
.TP
.B \-v
may be called multiple times to increase verbosity
.SH EXAMPLES
airpwn -i ath0raw -d madwifi -c conf/airpwned_img -v
.PP
airpwn -i ath0 -I ath0raw -d madwifi -c conf/airpwned_img -F -k 11:22:33:44:55 -v -v -v
.br
.SH NOTES
This utility was first demonstrated at Defcon 12.
.br
.SH BUGS
There are no known bugs at this time.
.SH AUTHOR
airpwn was written by Bryan Burns <toast@users.sourceforge.net>.
.br
This manual page was written by Jacob Appelbaum <jacob@appelbaum.net>
.br
.SH WEBSITE
<http://airpwn.sourceforge.net>
